language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
# cache: cargo
rust:
  - nightly
script:
- cargo tarpaulin --verbose --timeout 120 --out Xml --no-default-features --features safe-encode --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
- cargo tarpaulin --verbose --timeout 120 --out Xml --no-default-features --features safe-decode --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
- cargo tarpaulin --verbose --timeout 120 --out Xml --no-default-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

before_cache: |
  cargo install cargo-tarpaulin
