[package]
name = "lz4_flex"
version = "0.1.0"
authors = ["Pascal Seitz <pascal.seitz@gmail.com>", "ticki <Ticki@users.noreply.github.com>"]
edition = "2018"
description = "Pure Rust implementation of raw LZ4 compression/decompression."
repository = "https://github.com/pseitz/lz4_flex"
keywords = ["compression", "lz4", "compress", "decompression", "decompress"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
quick-error = "1.2.3"
# Only temp for profiling
# cpuprofiler = "0.0.4"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = "unwind"


[profile.bench]
codegen-units = 1
debug = false
lto = true
opt-level = 3
panic = "unwind"

[dev-dependencies]
criterion = "0.3.1"
lz4-compress = "0.1.1"
lz4 = "1.23.1"
brotli = "3.3.0"

# [[bin]]
# name = "profile_comp"
# [[bin]]
# name = "profile_decomp"
[[bin]]
name = "profile_comp"

[[bench]]
name = "bench"
harness = false


[features]
# no features by default
default = []

safe-decode = []