[package]
authors = ["Pascal Seitz <pascal.seitz@gmail.com>", "ticki <Ticki@users.noreply.github.com>"]
description = "Fastest LZ4 implementation in Rust, no unsafe by default."
edition = "2018"
keywords = ["compression", "lz4", "compress", "decompression", "decompress"]
name = "lz4_flex"
homepage = "https://github.com/pseitz/lz4_flex"
repository = "https://github.com/pseitz/lz4_flex"
readme = "README.md"
license = "MIT"
version = "0.6.1"
include = ["src/lib.rs", "src/frame/**/*", "src/block/**/*", "README.md"]

[[bench]]
harness = false
name = "crit_bench"
path = "benches/crit_bench.rs"

[dev-dependencies]
criterion = "0.3.3"
lz4 = "1.23.1"
lz4-compress = "0.1.1"
more-asserts = "0.2.1"

[dev-dependencies.lz-fear]
git = "https://github.com/main--/rust-lz-fear"

[features]
default = ["std", "safe-encode", "safe-decode"]
safe-decode = []
safe-encode = []
checked-decode = []
std = []

[profile.bench]
codegen-units = 1
debug = false
lto = true
opt-level = 3

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = "unwind"


# [[bench]]
# harness = false
# name = "quickbench"
# path = "benches/quickbench.rs"

# [[bench]]
# harness = false
# name = "bench"
# path = "benches/bench.rs"

# [[bin]]
# name = "decompress_with_stats"
# path = "src/test_bins/decompress_with_stats.rs"

# [[bin]]
# name = "profile_comp"
# path = "src/test_bins/profile_comp.rs"
