name:                           coverage

on:                             [push]
jobs:
  test:
    name:                       coverage
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin
      options:                  --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2

      - name: Generate code coverage
        run: cargo tarpaulin --verbose --workspace --timeout 120 --out Xml --all-features
      - name:                   Upload to codecov.io 1
        uses:                   codecov/codecov-action@v1
        with:
          fail_ci_if_error:     true
      - name: Generate code coverage --features safe-encode
        run: cargo tarpaulin --verbose --workspace --timeout 120 --out Xml --no-default-features --features safe-encode
      - name:                   Upload to codecov.io 2
        uses:                   codecov/codecov-action@v1
        with:
          fail_ci_if_error:     true
      - name: Generate code coverage safe-decode
        run: cargo tarpaulin --verbose --workspace --timeout 120 --out Xml --no-default-features --features safe-decode
      - name:                   Upload to codecov.io 3
        uses:                   codecov/codecov-action@v1
        with:
          fail_ci_if_error:     true
      - name: Generate code coverage no-default-features
        run: cargo tarpaulin --verbose --workspace --timeout 120 --out Xml --no-default-features
      - name:                   Upload to codecov.io 4
        uses:                   codecov/codecov-action@v1
        with:
          fail_ci_if_error:     true
