name:                           coverage

on:                             [push]
jobs:
  test:
    name:                       coverage
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin
      options:                  --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2

      - name: Generate code coverage
        run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
      - name: Generate code coverage --features safe-encode
        run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml --features safe-encode
      - name: Generate code coverage safe-decode
        run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml --features safe-decode
      - name: Generate code coverage no-default-features
        run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml --no-default-features

      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v1
        with:
          # token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error:     true
