name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test safe-encode
    - name: Run tests --features safe-encode
      run: cargo test --features safe-encode --verbose
    - name: Run tests safe-decode
      run: cargo test --verbose --features safe-decode
    - name: Run tests no-default-features (no safe-decode)
      run: cargo test --verbose --no-default-features
    - name: Make Sure safe-encode does not include unsafe in compression
      run: |
        cargo install cargo-expand
        cargo install assert_contains_cli
        cargo expand --features safe-encode --lib block::compress | assert_contains_not unsafe
