name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
    - name: Run tests --features safe-encode
      run: cargo test --features safe-encode --verbose
    - name: Run tests safe-decode
      run: cargo test --verbose --features safe-decode
    - name: Run tests no-default-features (no safe-decode)
      run: cargo test --verbose --no-default-features
